build: false
platform:
  - x64
clone_folder: c:\projects\php-project-workspace

## Build matrix for lowest and highest possible targets
environment:
  matrix:
  - dependencies: highest
    php_ver_target: 7.3.11

## Set up environment variables
init:
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHP=1 # This var is connected to PHP install cache
    - SET ANSICON=121x90 (121x90)

## Install PHP and composer, and run the appropriate composer commandand XDEBUG
install:
    # Enable Windows Update service, needed to install vcredist2015 (dependency of php)
    - IF EXIST c:\tools\php73 (SET PHP=0)
    - ps: Set-Service wuauserv -StartupType Manual
    - choco config set cacheLocation %LOCALAPPDATA%\Temp\Chocolatey
    - choco install -y php --version %php_ver_target%
    - choco install -y composer
    - refreshenv
    - composer install --no-interaction --no-progress --prefer-dist
    - cd C:\tools\php73
    - IF %PHP%==1 copy php.ini-production php.ini /Y
    - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
    - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
    - IF %PHP%==1 echo extension=php_sockets.dll >> php.ini
    - ps: >-
        If ($env:PHP -eq "1") {
            Invoke-WebRequest "https://windows.php.net/downloads/pecl/releases/uv/0.2.4/php_uv-0.2.4-7.3-nts-vc15-x64.zip" -OutFile "php_uv-0.2.4-7.3-nts-vc15-x64.zip"
            7z x -y php_uv-0.2.4-7.3-nts-vc15-x64.zip libuv.dll php_uv.dll
            copy php_uv.dll ext\php_uv.dll
            del php_uv.dll
            del php_uv-0.2.4-7.3-nts-vc15-x64.zip
            Invoke-WebRequest "https://xdebug.org/files/php_xdebug-2.7.2-7.3-vc15-nts-x86_64.dll" -OutFile "C:\tools\php73\ext\php_xdebug-2.7.2-7.3-vc15-nts-x86_64.dll"
        }
    - IF %PHP%==1 echo extension=php_uv.dll >> php.ini
    - IF %PHP%==1 echo [xdebug] >> php.ini
    - IF %PHP%==1 echo zend_extension=php_xdebug-2.7.2-7.3-vc15-nts-x86_64.dll >> php.ini
    - IF %PHP%==1 echo zend.assertions=1 >> php.ini
    - IF %PHP%==1 echo assert.exception=On >> php.ini
    - IF %PHP%==1 echo xdebug.remote_enable=1 >> php.ini
    - IF %PHP%==1 echo xdebug.remote_autostart=1 >> php.ini
    - IF %PHP%==1 echo xdebug.profiler_enable=off >> php.ini
    - cd c:\projects\php-project-workspace
    - composer self-update

on_success:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"

## Run the actual test
test_script:
    - cd c:\projects\php-project-workspace
    - vendor\bin\phpunit --coverage-clover=coverage.xml
